---
title: "Quantum Fourier Trafo"
author: "Carsten Urbach"
output:
  rmarkdown::html_vignette
    
vignette: >
  %\VignetteIndexEntry{qft}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r echo=FALSE}
library(knitr)
library(qsimulatR)
knitr::opts_chunk$set(fig.align='center',
                      comment='')
```

# Three qubit QFT

Let's take a normalised vector with eight components and Fourier transform it

```{r}
N <- 3
v <- seq(1:2^N)
#v <- rep(1., 2^N)
#v <- c(1, 1, 1, 1, 0, 0, 0, 0)
v <- v/sqrt(sum(v^2))

#v <- c(1, rep(0, 7))
w <- fft(v)
w/sqrt(length(w))
```

The same using the quantum Fourier Trafo

```{r}
y <- qstate(N, coefs=as.complex(v))
x <- H(3) * y
x <- cqgate(bits=c(2L, 3L), gate=S(3L)) * x
x <- cqgate(bits=c(1L, 3L), gate=Tgate(3L)) * x
x <- H(2) * x
x <- cqgate(bits=c(1L, 2L), gate=S(2L)) * x
x <- H(1) * x
x <- SWAP(c(1,3)) * x
```


```{r}
plot(x)
```

Now the coefficients of the state `x` should be the the Fourier
transform of the coefficients of `y`. The QFT is unitary

```{r}
sum(x@coefs*Conj(x@coefs))
```

and the coefficients match the one from the classical FFT

```{r}
x@coefs
```
