#' export2qasm
#'
#' Export to IBM's QASM
#' 
#' @description
#' export a circuit to IBM's QASM qiskit python format. Note that only
#' gates can be exported where the correspondence is known to QASM
#'
#' @details
#' Currently the following gates can be exported: H, X, Y, Z, S,
#' Tgate, Rz, CNOT, SWAP, CCNOT, CSWAP, measure.
#' 
#' @param object a qstate object
#' @param filename character. The filename of the textfile where to store the circuit
#' @param append boolean. Whether or not to append to the file. For this the file has to exist.
#'
#' @include state.R
#'
#' @references
#' https://qiskit.org/documentation/
#' 
#' @return
#' nothing is returned, but a file is created.
#' 
#' @examples
#' x <- qstate(2)
#' x <- H(1) * x
#' x <- X(2) * x
#' x <- CNOT(c(1,2)) * x
#' export2qasm(measure(x,1)$psi)
#' 
#' @export
export2qasm <- function(object, filename="circuit.py", append=FALSE) {
  if(!append) file.create(filename)
  olines <- c("# automatically generated by qsimulatR",
              paste0("qc = QuantumCircuit(", object@nbits, ",", object@circuit$ncbits, ")"))
  ngates <- length(object@circuit$gatelist)
  if(ngates > 0) {
    for(i in c(1:ngates)) {
      op <- ""
      if(object@circuit$gatelist[[i]]$type == "H") op <- paste0("h(", object@circuit$gatelist[[i]]$bits[1]-1, ")")
      if(object@circuit$gatelist[[i]]$type == "X") op <- paste0("x(", object@circuit$gatelist[[i]]$bits[1]-1, ")")
      if(object@circuit$gatelist[[i]]$type == "Y") op <- paste0("y(", object@circuit$gatelist[[i]]$bits[1]-1, ")")
      if(object@circuit$gatelist[[i]]$type == "Z") op <- paste0("z(", object@circuit$gatelist[[i]]$bits[1]-1, ")")
      if(object@circuit$gatelist[[i]]$type == "S") op <- paste0("s(", object@circuit$gatelist[[i]]$bits[1]-1, ")")
      if(object@circuit$gatelist[[i]]$type == "Tgate") op <- paste0("t(", object@circuit$gatelist[[i]]$bits[1]-1, ")")
      if(object@circuit$gatelist[[i]]$type == "Rz") op <- paste0("rz(", object@circuit$gatelist[[i]]$angle, ",", object@circuit$gatelist[[i]]$bits[1]-1, ")")
      if(object@circuit$gatelist[[i]]$type == "CNOT") op <- paste0("cx(", object@circuit$gatelist[[i]]$bits[1]-1, ",", object@circuit$gatelist[[i]]$bits[2]-1, ")")
      if(object@circuit$gatelist[[i]]$type == "SWAP") op <- paste0("swap(", object@circuit$gatelist[[i]]$bits[1]-1, ",", object@circuit$gatelist[[i]]$bits[2]-1, ")")
      if(object@circuit$gatelist[[i]]$type == "CCNOT") op <- paste0("ccx(", object@circuit$gatelist[[i]]$bits[1]-1, ",", object@circuit$gatelist[[i]]$bits[2]-1, ",", object@circuit$gatelist[[i]]$bits[3]-1, ")")
      if(object@circuit$gatelist[[i]]$type == "CSWAP") op <- paste0("cswap(", object@circuit$gatelist[[i]]$bits[1]-1, ",", object@circuit$gatelist[[i]]$bits[2]-1, ",", object@circuit$gatelist[[i]]$bits[3]-1, ")")
      if(object@circuit$gatelist[[i]]$type == "measure") op <- paste0("measure([", object@circuit$gatelist[[i]]$bits[1]-1, "],[", object@circuit$gatelist[[i]]$bits[2]-1, "])")
      olines <- c(olines, paste0("qc.", op))
    }
  }
  fc <- NULL
  if(append) fc <- file(filename, open="at")
  else fc <- file(filename)
  writeLines(text=olines, con=fc)
  close(fc)
}
